#ifndef _ERROR_H_
#define _ERROR_H_

enum STATUSCODE
{
    ACCEL_SUCCESS = 0,
    ACCEL_ERROR_FAILED,
    ACCEL_ERROR_UNEXPECTED,
    ACCEL_ERROR_INVALID_ARGUMENT,
    ACCEL_ERROR_INSUFFICIENT_BUFFER,
    ACCEL_ERROR_NOT_IMPLIMENTED
};

#endif
